export const pssMdxMap: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  '2008': () => import('@/app/policies/data/pss/2008.mdx'),
  '2009': () => import('@/app/policies/data/pss/2009.mdx'),
  '2010': () => import('@/app/policies/data/pss/2010.mdx'),
  '2011': () => import('@/app/policies/data/pss/2011.mdx'),
  '2012': () => import('@/app/policies/data/pss/2012.mdx'),
  '2013': () => import('@/app/policies/data/pss/2013.mdx'),
  '2014': () => import('@/app/policies/data/pss/2014.mdx'),
  '2015': () => import('@/app/policies/data/pss/2015.mdx'),
  '2016': () => import('@/app/policies/data/pss/2016.mdx'),
  '2017': () => import('@/app/policies/data/pss/2017.mdx'),
  '2018': () => import('@/app/policies/data/pss/2018.mdx'),
  '2019': () => import('@/app/policies/data/pss/2019.mdx'),
  '2020': () => import('@/app/policies/data/pss/2020.mdx'),
  '2021': () => import('@/app/policies/data/pss/2021.mdx'),
  '2022': () => import('@/app/policies/data/pss/2022.mdx'),
  '2023': () => import('@/app/policies/data/pss/2023.mdx'),
  '2024': () => import('@/app/policies/data/pss/2024.mdx'),
  'animal-rights': () => import('@/app/policies/data/pss/animal-rights.mdx'),
  'climate-emergency': () => import('@/app/policies/data/pss/climate-emergency.mdx'),
  countryside: () => import('@/app/policies/data/pss/countryside.mdx'),
  'crime-and-justice': () => import('@/app/policies/data/pss/crime-and-justice.mdx'),
  'culture-media-and-sports': () => import('@/app/policies/data/pss/culture-media-and-sports.mdx'),
  disability: () => import('@/app/policies/data/pss/disability.mdx'),
  'drugs-policy': () => import('@/app/policies/data/pss/drugs-policy.mdx'),
  education: () => import('@/app/policies/data/pss/education.mdx'),
  energy: () => import('@/app/policies/data/pss/energy.mdx'),
  europe: () => import('@/app/policies/data/pss/europe.mdx'),
  'finance-amp-economy': () => import('@/app/policies/data/pss/finance-amp-economy.mdx'),
  'food-and-agriculture': () => import('@/app/policies/data/pss/food-and-agriculture.mdx'),
  forestry: () => import('@/app/policies/data/pss/forestry.mdx'),
  health: () => import('@/app/policies/data/pss/health.mdx'),
  'heritage-and-tourism': () => import('@/app/policies/data/pss/heritage-and-tourism.mdx'),
  housing: () => import('@/app/policies/data/pss/housing.mdx'),
  'industry-and-jobs': () => import('@/app/policies/data/pss/industry-and-jobs.mdx'),
  'interim-policy': () => import('@/app/policies/data/pss/interim-policy.mdx'),
  international: () => import('@/app/policies/data/pss/international.mdx'),
  land: () => import('@/app/policies/data/pss/land.mdx'),
  'local-planning-and-the-built-environment': () =>
    import('@/app/policies/data/pss/local-planning-and-the-built-environment.mdx'),
  'marine-and-coastal': () => import('@/app/policies/data/pss/marine-and-coastal.mdx'),
  migration: () => import('@/app/policies/data/pss/migration.mdx'),
  nationality: () => import('@/app/policies/data/pss/nationality.mdx'),
  'natural-resources-and-waste-management': () =>
    import('@/app/policies/data/pss/natural-resources-and-waste-management.mdx'),
  'our-political-programme': () => import('@/app/policies/data/pss/our-political-programme.mdx'),
  'peace-security-and-defence': () =>
    import('@/app/policies/data/pss/peace-security-and-defence.mdx'),
  'philosophical-basis': () => import('@/app/policies/data/pss/philosophical-basis.mdx'),
  'policies-for-a-sustainable-society': () =>
    import('@/app/policies/data/pss/policies-for-a-sustainable-society.mdx'),
  policies: () => import('@/app/policies/data/pss/policies.mdx'),
  policy: () => import('@/app/policies/data/pss/policy.mdx'),
  pollution: () => import('@/app/policies/data/pss/pollution.mdx'),
  population: () => import('@/app/policies/data/pss/population.mdx'),
  'public-administration-and-government': () =>
    import('@/app/policies/data/pss/public-administration-and-government.mdx'),
  'record-of-policy-statements-rops': () =>
    import('@/app/policies/data/pss/record-of-policy-statements-rops.mdx'),
  'refugees-and-asylum': () => import('@/app/policies/data/pss/refugees-and-asylum.mdx'),
  'responsibilities-amp-rights': () =>
    import('@/app/policies/data/pss/responsibilities-amp-rights.mdx'),
  'science-amp-technology': () => import('@/app/policies/data/pss/science-amp-technology.mdx'),
  'social-welfare': () => import('@/app/policies/data/pss/social-welfare.mdx'),
  'the-green-party-s-core-values': () =>
    import('@/app/policies/data/pss/the-green-party-s-core-values.mdx'),
  transport: () => import('@/app/policies/data/pss/transport.mdx'),
  'wildlife-and-habitats': () => import('@/app/policies/data/pss/wildlife-and-habitats.mdx'),
  'workers-rights-and-employment': () =>
    import('@/app/policies/data/pss/workers-rights-and-employment.mdx'),
}
